### ISSUE TITLE
Implement Standard Pruned Grid

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#112] opened 2021-04-05 23:45 UTC
Implement SG1 as mentioned in issue #12.

**Comment by PaulWAyers** [comment] 2021-04-06 00:02
There are a number of standard(ish) pruned grids. We already support the HORTON2 pruned grids. 

The Gaussian pruned grids are:
https://gaussian.com/integral/#:~:text=%E2%80%9CPruned%E2%80%9D%20grids%20are%20grids%20that,defined%20for%20H%20through%20Kr.

The SG-n grids are the standard in Q-Chem
https://manual.q-chem.com/5.1/sect-quadrature.html

Finally there are the Ochsenfeld grids (which are especially amenable to the sector/points methods we use to define grids). See table 3 in:
J. Chem. Phys. 149, 204111 (2018)
https://doi.org/10.1063/1.504

To me, the SG-n grids and the Ochsenfeld grids would be higher priority than the Gaussian grids, but the Gaussian grids would be probably more useful in terms of compatability......

**Comment by leila-pujal** [comment] 2021-07-13 18:17
I've started to implement the standard grids from q-chem but I have some questions. Basically standard grids are pruned grids that use a specific scheme to create the atomic grids. I already have a code to obtain a molecular grid with this specific pruned atomic grids for the atoms composing the system, but I am having difficulties to find the one dimensional grid and transformation inside `grid` package that correspond to the ones specified in the papers. Below I list the different standard grids defined in qchem that I am working to implement and so far the things I found inside grid:

- SG-0 -  Multiexponential scheme: In the paper ([SG-0: A Small Standard Grid for DFT Quadrature on Large Systems.pdf](https://github.com/theochem/grid/files/6810930/SG-0.A.Small.Standard.Grid.for.DFT.Quadrature.on.Large.Systems.pdf)) for the SG-0 they defined the multiexponential grid as a combination of a logarithmic transformation and a “log-squared” quadrature yielding the multiexponential grid with the following transform, points, and weights.
![image](https://user-images.githubusercontent.com/61252051/125500624-233c1a56-4475-4e02-b295-b4c80be8ebeb.png)

In the `rtransform.py` module there’s a `MultiExpTF` but I think it doesn’t match with the characteristics of the Multiexponential grid the authors defined in the paper.
https://github.com/theochem/grid/blob/d3d0590ad6f82c926cf6ef68349a6dd3ea204d1e/src/grid/rtransform.py#L919

- SG-1 - Euler maclaurin scheme. In the paper for SG-1 (
[1-s2.0-0009261493801259-main.pdf](https://github.com/theochem/grid/files/6810959/1-s2.0-0009261493801259-main.pdf) They define the following specifications for transform, points and weights (image showed taken from this paper(
[El-Sherbiny, Poirier - 2004 - An evaluation of the radial part of numerical integration commonly used in DFT.pdf](https://github.com/theochem/grid/files/6810969/El-Sherbiny.Poirier.-.2004.-.An.evaluation.of.the.radial.part.of.numerical.integration.commonly.used.in.DFT.pdf) because it is showed more clear)
![image](https://user-images.githubusercontent.com/61252051/125501442-e838b5b0-e76c-47a7-8e89-08af9a041844.png)

There’s a one radial grid type in the module that is supposed to relate to this one under the name of `Trapezoidal`,
https://github.com/theochem/grid/blob/d3d0590ad6f82c926cf6ef68349a6dd3ea204d1e/src/grid/onedgrid.py#L262
 but comparing equations defined inside the function and the ones reported in some papers I think they are different? and also here the mapping/transformation is not yet taken into account. 

- SG-2 and SG-3 - Double exponential scheme: In the paper [jcc.24761.pdf](https://github.com/theochem/grid/files/6810995/jcc.24761.pdf) they specify the following transform weights and points. 
![image](https://user-images.githubusercontent.com/61252051/125502124-f635754b-d020-45ec-9eca-60886e8c4895.png)
![image](https://user-images.githubusercontent.com/61252051/125502140-873bf781-5179-4418-95c9-fb2c5f328faa.png)
![image](https://user-images.githubusercontent.com/61252051/125502181-3b899ce0-679a-4761-9f5f-c42edd53c8d0.png)
They said in the paper that this Double exponential is also known “tanh-sinc” quadrature. Inside `onedgrid.py` and `rtransform.py` there's `TanhSinh` and `ExpRTransform` functions but I am not sure if they are the same reported in the paper. 
https://github.com/theochem/grid/blob/d3d0590ad6f82c926cf6ef68349a6dd3ea204d1e/src/grid/onedgrid.py#L406
https://github.com/theochem/grid/blob/d3d0590ad6f82c926cf6ef68349a6dd3ea204d1e/src/grid/rtransform.py#L669

My doubts would be the same for all the SG aforementioned, I apologize beforehand if there's something obvious that I ignored or if I said something wrong. So my questions would be,  am I right with the information I reported before or some of the one dimensional grids/transforms I pointed out are in fact the correct ones? If not, can I still generate the different atomic grid schemes that I need for creating the different SG by using some combination of one dimensional grids/transform that is already coded inside grid? If not do I need to code these schemes? Help answering these questions will be much appreciate it, @FarnazH, @tczorro, @PaulWAyers.

**Comment by leila-pujal** [comment] 2021-07-13 22:22
Update: I was looking at the Ochsenfeld grids ([1.5049435.pdf](https://github.com/theochem/grid/files/6812262/1.5049435.pdf)) and I have more or less the same situation than with the SG. Here they use Chebyshev quadrature of the second kind with a specific transformation to obtain the Ahlrichs atomic grid:
![image](https://user-images.githubusercontent.com/61252051/125532457-e2cf59d3-08df-421d-9e49-34ff2c4b3014.png)

I know that `GaussChebyshevType2` is implemented but I couldn't find the corresponding transformation. However, I took a quick look at the grid notes and came accros this part:
![image](https://user-images.githubusercontent.com/61252051/125532628-74fab817-05f3-467e-a158-5f1f804491b0.png)
You didn't plan to include it in grid?

**Comment by FarnazH** [comment] 2021-07-14 05:53
@leila-pujal thanks for your update and detailed post. We are going to only implement the angular part of these pruned grids, so there is no need to find the 1DGrid and transformation that corresponds to the ones in the paper. We allow the user to combine these pruned angular grids with any radial grid, and have talked about adding a decent default radial grid as well (i.e., making radial grid an optional argument).

I think the problem is that these 1DGrid & transformations are not standardized, so it is not surprising that they don't match what we have implemented, but it would be good to double check.

**Comment by PaulWAyers** [comment] 2022-05-19 18:28
@FarnazH reminded me of this discussion. We can implement specific grids like these, but the first thing to do is just have the sectors. In general, the very specific radial grid is not that important (and Euler-Maclaurin is often very good), but having good segmentation stategies is important. So I'd take these grids and define them as segments. In the end, these segmentation strategies with whatever we (eventually) determine to be the best radial grid/transformation/partitioning will work well.

I'd just do compute the sectors for these then. We can support the radial grids, and the various double-exponentials and tanh-sinh are implemented, as is Euler-Maclaurin.

**Comment by PaulWAyers** [comment] 2022-05-19 18:34
Looking in more detail:
Ochsenfeld seems pretty straightforward. 
- It has a prescription for the number of radial points (per atom). (Table III and Eq. A6).
- It has a prescription for the degree of the angular shells for each of three regions (Table III).
- The cutoff points for the sectors can be computed from Table II, Eqs. A2 and A4. That allows the sectors.

**Comment by PaulWAyers** [comment] 2022-05-19 19:16
The SG-n grids are relatively similar. So looking at the papers the key info is available for the too. 

So the idea would be that each of these grids defines:
- for each supported element, a number of radial points, a definition of sectors, a specified angular grid for each sector.
We would probably use the default radial grid for `grid`; I'm not sure how hard it is to tether this to a specified radial grid.

Note that the SG-n grids aren't defined for all atoms.

**Comment by leila-pujal** [comment] 2022-05-20 20:44
Thanks a lot @PaulWAyers (and @FarnazH for the previous comments) for your detail answers. I just did a PR #147 of the function to create the pruned grids. I hope I understood correctly what you wanted to implement, but let me know in the PR if I misunderstood the goal of the function. Also, I need help/verification with something related to the Ochsenfeld grids. So Table III gives the specifications of each pruned grid with the number of points and angular for each sector defined in A5. Then it says that for each row in the periodic table you ad extra radial points according to A6. What I understand from the paper is that we obtain the points for each sector of angular grid (inner, medium, outer) for **n_rad** and **n_rad_extra** separately. So in the specific case of carbon and g1 grid this would be:

For n_rad = 35
inner limit 35/3 = 11.6 --> points in inner sector = from 1 to 11 = 11
outer limit 35/2 = 17.5 --> points in medium sector = from 11 to 17 = 6
 --> points in outer sector = from 18 to 35 = 18 


For n_rad_extra = 5
inner limit 5/3 = 1.6 --> points in inner sector = 1
outer limit 5/2 = 2.5 --> points in medium sector = 1
		          --> points in outer sector = 3

Total points in each sector:
inner = 12
medium = 7
outer = 21

But if I multiply each sector by its angular size I don’t get back what they report back as the total number of grid points for carbon:

Reported paper = 2586

inner = 12 x 14 = 168
medium = 7 x 50 = 350
outer = 21 x 110 = 2310   Total = 2828

Even if I only take into account the 35 points only I would get:

inner = 11 x 14 = 154
medium = 6 x 50 = 300
outer = 18 x 110 = 1980   Total = 2434

I have generated the npz I added in the PR using the first approach (combine n_rad + n_extra) but at this points I don’t know what I am doing wrong. I checked [reference 6](https://aip.scitation.org/doi/abs/10.1063/1.469408?casa_token=phfVFNYiUtoAAAAA:bXNvmA9fdansrmvLOzCpNThhQQKngoMzboperAr6VsiCGoO9ea-SgAwd9FrDApbaE-RpuKVBRos) in their paper because they take the pruning scheme from there and I believe I obtained correctly inner, medium and outer number of points for the ones reported in ref(6) table III. Any help on this would be appreciate it.

**Comment by PaulWAyers** [comment] 2022-05-22 01:56
It's tricky because the paper isn't very specific. It's worse than that. I can reproduce the numbers but it isn't very systematic. 

- The g1 grid has 40 radial points for Carbon. I can reproduce the number of points with: 
2586 = 14*(40//3+1) + 50*(40//2-40//3-1) + 110*(40-40//2-1) = 2586
I would interpet this as (a) there is a tau=0 indexed point; (b) the point corresponding to tau=20 is included in the "outer" region rather than the "medium" region.

- The g2 grid has 45 radial points for Carbon. 
26*(45//3) + 74*(45//2 - 45//3+1) + 194*(45-45//2-2) = 5056
I would interpret this as (a) there is a tau=0 indexed point (b) the point corresponding to tau=15 is included in the "medium" region rather than the "inner" region. (c) the "minus two" occurs because the last point is tau=44 (not tau=45) and the tau=45//2=22 point is included in the "medium" region.

- The g3 grid has 55 radial points for Carbon
38*(55//3+1) + 110*(55//2-55//3) + 302*(55 - 55//2 - 2) = 9564
again there is a tau=0 point, and this seems (somewhat) consistent.

- The g4 grid has 60 radial points for Carbon
50*(60//3) + 194*(60//2-60//3) + 434*(60 - 60//2 - 1) = 15526
(a) there is a tau=0 point, but the tau=20 point is assigned to the medium region. (b) the tau=30 point is assigned to the "outer" region.

- The g5 grid has 65 radial points for Carbon
50*(65//3+1) + 194*(65//2-65//3-1) + 590*(65 - 65//2 - 2) = 21330

- The g6 grid has 75 radial points for Carbon:
86*(75//3) + 302*(75//2-75//3) + 974*(75 - 75//2 - 2) == 40838
(this makes sense if the 75/3 point is shifted from the "inner" to the "medium" grid)

- The g7 grid has 85 radial points for Carbon: 
110*(85//3) +434*(85//2 - 85//3)+(85-85//2-2)*1454 = 68770

So the essence seems to be that:
Shells from tau=0,1,2,....nrad//3 are "inner" unless nrad/3 is an integer.
Shells from tau=nrad//3+1,....nrad//2 are "medium" unless nrad/3 or nrad/2 is an integer.
Shells from tau=nrad//2+1,...nrad-2 are "outer" unless nrad/2 is an integer.
(It's crazy, but the actual number of radial points is one less than reported in the paper!)

if nrad/3 is an integer, tau=nrad/3 is "medium"
if nrad/2 is an integer, tau=nrad/2 is "outer"

The most complicated case (for Carbon) is then the g4 grid, with 60 points.
tau=0,1,2,....19 are "inner" (20 points)
tau=20,21,....29 are "medium" (10 points)
tau=30,31,....58 are "outer" (30 points) 

Double-checking a couple other cases to confirm. For the g1 grid there are 40 points:
tau=0,1,2,...13 are inner (14 points)
tau=14,15,....19 are medium (6 points)
tau=20,21,....38 are outer (19 points)

So I think this is what the Ochsenfeld grids really do, but it's pretty unbelievable.

**Comment by leila-pujal** [comment] 2022-05-22 17:14
Omg...this is worst than I thought. I thought I was doing some basic mistake but I was not expecting this multiverse of madness. While I was trying to figure out the points I arrive at the point where I could reproduce the number by adding X number of radial points to specific sectors but it was different for each grid and sometimes I think it never add up to any total number of radial points. That's why end up asking for help on this. I will check in more detail your message and regenerate the npz files with the correct radial points sectors. Thanks a lot for the help @PaulWAyers

**Comment by PaulWAyers** [comment] 2022-05-23 20:34
Yep, it's messy. It isn't *that* important as adding one extra radial point, or shifting one point to/from inner/middle or middle/outer isn't going to make the grid significantly worse.

**Comment by PaulWAyers** [comment] 2022-05-27 14:55
@leila-pujal you mentioned in the meeting yesterday that there was an issue? If there is a problem, let me know and I'll try to figure it out by early next week.

**Comment by leila-pujal** [comment] 2022-05-27 22:38
@PaulWAyers, thanks again for taking the time to look at this. Just to mention this has very low priority (we have the meeting in two weeks).Anyway, I tried to follow the instructions from your message for getting the radial points for each sector:

>So the essence seems to be that:
>Shells from tau=0,1,2,....nrad//3 are "inner" unless nrad/3 is an integer.
>Shells from tau=nrad//3+1,....nrad//2 are "medium" unless nrad/3 or nrad/2 is an integer.
>Shells from tau=nrad//2+1,...nrad-2 are "outer" unless nrad/2 is an integer.
>(It's crazy, but the actual number of radial points is one less than reported in the paper!)
>if nrad/3 is an integer, tau=nrad/3 is "medium"
>if nrad/2 is an integer, tau=nrad/2 is "outer"

This worked perfectly except for g5 g6 and g7. I report what I obtained 
g5, nrad=65  65/3=21.6, 65/2=32.5;
inner: tau=0,1,2...21(22 points)
medium: tau=22,23...,32 (11points)
outer: tau=33,34...63( 31 points)
total= 22 *50 + 11 *194 + 31 *590 = 21524 --- reported = 21330 (diference is 194, size of the medium sector)

g6, nrad=75  75/3=25, 75/2=37.5;
inner: tau=0,1,2...24(25 points)
medium: tau=25,26...,37 (13 points)
outer: tau=38,39...73( 36 points)
total=25 *86 + 13 *302 + 36 *974 = 41140 --- reported =40838 (difference is 302, size of medium sector)

g6, nrad=85  85/3=28.3, 85/2=42.5;
inner: tau=0,1,2...28(29 points)
medium: tau=29,30...,42 (14 points)
outer: tau=43,44...83( 41 points)
total=29 *110 + 14 *434 + 41 *1454 = 68880 --- reported =68770 (difference is 110 size of the inner sector)

Maybe I am doing some obvious mistake somewhere in obtaining the points for each sector. In case I am not, then it looks like we have one point less for these 3 grids? You could figure it out the first time so probably you can see more clearly what's the problem. Thanks again for the help.

**Comment by PaulWAyers** [comment] 2022-05-30 17:12
For g5, the numbers that work are:
50*(65//3+1) + 194*(65//2-65//3-1) + 590*(65 - 65//2 - 2)
or
50*22+194*10 + 590*31
I agree, this is only 63 points. Crazy. 

I have the "codes" (you figure them out too) for all of these. I don't think it is worth trying to figure them out further. I would, honestly, choose a bona fide grid with the number of points in the Ochsenfeld paper (even though the description in that paper is clearly wrong), and then just group as:
0,1,2,...(nrad-1)//3
(nrad-1)//3,....(nrad-1)//2
(nrad-1)//2,....(nrad-2),(nrad-1)

What do you think @FarnazH ? This would match the description in the paper, and if it does not match the actual numbers reported, it's only because we (effectively) debugged their code....

**Closed** 2023-11-17 15:26 UTC
Labels: enhancement
